const fs = require('fs');
let html = fs.readFileSync('htmlDesktop.html', 'utf-8');
html = html.replace(/<body[^>]*>/i, '');
html = html.replace(/<\/body>/i, '');
html = html.replace(/class="/g, 'className="');
html = html.replace(/for="/g, 'htmlFor="');
html = html.replace(/<img([^>]*?)(?<!\/)>/ig, '<img$1 />');
html = html.replace(/<input([^>]*?)(?<!\/)>/ig, '<input$1 />');
html = html.replace(/<hr([^>]*?)(?<!\/)>/ig, '<hr$1 />');
html = html.replace(/<br([^>]*?)(?<!\/)>/ig, '<br$1 />');
html = html.replace(/brick="\[object Object\]"/g, '');
html = html.replace(/style="font-size:16px"/g, "style={{ fontSize: '16px' }}");
html = html.replace(/style="font-size:10px;margin-top:2px"/g, "style={{ fontSize: '10px', marginTop: '2px' }}");
html = html.replace(/style="font-size:18px"/g, "style={{ fontSize: '18px' }}");
html = html.replace(/style="font-size:10px;margin-top:3px"/g, "style={{ fontSize: '10px', marginTop: '3px' }}");
html = html.replace(/content_hover="[^"]*"/g, '');
fs.writeFileSync('desktopJsx.txt', html, 'utf-8');
